"""Probabilistic forecast contracts."""

from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class QuantilePoint(BaseModel):
    """Predicted values across quantiles at a single horizon step."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    timestamp: datetime
    step_index: int
    duration_hours: float
    q05: float
    q10: float
    q25: float
    q50: float  # Median
    q75: float
    q90: float
    q95: float

    @property
    def iqr(self) -> float:
        """Interquartile range."""
        return self.q75 - self.q25

    @property
    def interval_80(self) -> tuple[float, float]:
        """80% prediction interval (q10 to q90)."""
        return self.q10, self.q90


class StormProbability(BaseModel):
    """Storm onset probabilities across rolling forecast horizons."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    p_storm_3h: Annotated[float, Field(ge=0.0, le=1.0)]
    p_storm_6h: Annotated[float, Field(ge=0.0, le=1.0)]
    p_storm_12h: Annotated[float, Field(ge=0.0, le=1.0)]
    p_storm_24h: Annotated[float, Field(ge=0.0, le=1.0)]
    p_storm_48h: Annotated[float, Field(ge=0.0, le=1.0)]
    predicted_storm_type: str = Field(
        default="NONE", description="BLIZZARD, KATABATIC, WHITEOUT, or NONE"
    )
    expected_peak_wind_m_s: Annotated[float, Field(ge=0.0, default=0.0)]
    expected_duration_hours: Annotated[float, Field(ge=0.0, default=0.0)]


class VariableForecast(BaseModel):
    """Quantile series for a single forecasted variable."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    variable_name: str
    unit: str
    quantiles: list[QuantilePoint] = Field(..., min_length=1)
    conformal_coverage_target: Annotated[float, Field(ge=0.5, le=1.0, default=0.80)]
    conformal_calibrated_q10_offset: float = 0.0
    conformal_calibrated_q90_offset: float = 0.0


class Forecast(BaseModel):
    """Complete rolling forecast artifact generated by the forecasting engine."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    station_id: str
    issued_at: datetime
    horizon_hours: Annotated[float, Field(gt=0, default=72.0)]
    storm_probability: StormProbability
    wind_speed: VariableForecast
    wind_power_kw: VariableForecast
    solar_power_kw: VariableForecast
    ambient_temp_c: VariableForecast
    electrical_load_kw: VariableForecast
    thermal_heating_load_kw: VariableForecast

    @property
    def steps_count(self) -> int:
        return len(self.wind_speed.quantiles)
