"""Optimal energy plan contracts output by the scenario MPC."""

from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class PlanGensetStep(BaseModel):
    """Generator dispatch plan at a single time step."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    genset_id: str
    is_committed: bool = Field(description="Shared here-and-now binary commitment")
    is_starting: bool = Field(default=False)
    is_stopping: bool = Field(default=False)
    expected_power_kw: Annotated[float, Field(ge=0.0)]
    expected_fuel_rate_l_per_h: Annotated[float, Field(ge=0.0)]


class PlanBatteryStep(BaseModel):
    """Battery dispatch plan at a single time step."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    charge_power_kw: Annotated[float, Field(ge=0.0)]
    discharge_power_kw: Annotated[float, Field(ge=0.0)]
    expected_soc: Annotated[float, Field(ge=0.0, le=1.0)]
    dynamic_reserve_soc: Annotated[float, Field(ge=0.0, le=1.0)]


class PlanLoadStep(BaseModel):
    """Load scheduling and shedding plan at a single time step."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    tier: int
    scheduled_served_kw: Annotated[float, Field(ge=0.0)]
    scheduled_shed_kw: Annotated[float, Field(ge=0.0)]


class PlanStep(BaseModel):
    """Full system dispatch plan at step t."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    step_index: int
    timestamp: datetime
    duration_hours: float
    gensets: list[PlanGensetStep]
    battery: PlanBatteryStep
    loads: list[PlanLoadStep]
    indoor_temp_c: float
    aux_heating_kw: Annotated[float, Field(ge=0.0)]
    deferrable_power_kw: Annotated[float, Field(ge=0.0)]
    curtailed_wind_kw: Annotated[float, Field(ge=0.0, default=0.0)]
    curtailed_pv_kw: Annotated[float, Field(ge=0.0, default=0.0)]


class Plan(BaseModel):
    """Complete 72-hour operational schedule generated by the scenario MPC."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    plan_id: str
    generated_at: datetime
    horizon_hours: float
    steps: list[PlanStep] = Field(..., min_length=1)
    solver_status: str
    solve_time_seconds: float
    mip_gap: float
    expected_total_fuel_l: Annotated[float, Field(ge=0.0)]
    cvar_risk_value: Annotated[float, Field(ge=0.0)]
    fuel_shadow_price_usd_per_l: float = 0.0

    @property
    def immediate_step(self) -> PlanStep:
        """First step in the plan, used for immediate setpoints."""
        return self.steps[0]
